DRAFT: NodeJS 18x support
heremaps/here-data-sdk-typescript pull request #518
Opened 2024-04-29 19:10 UTC by OleksiiZubko

2024-05-09 08:59 UTC, ystefinko approved these changes

2024-05-09 11:09 UTC, HalynaDumych approved these changes

2024-05-09 11:11 UTC, HalynaDumych requested changes

2024-05-09 11:11 UTC, HalynaDumych commented on @here/olp-sdk-fetch/README.md
> +The main goal of this module is to provide possibility to read files from the local folders with `fetch` API in the Node.js environment.
```suggestion
The main goal of this module is to provide possibility to read files from the local folders with the `fetch` API in the Node.js environment.
```

2024-05-09 11:20 UTC, HalynaDumych requested changes

2024-05-09 11:20 UTC, HalynaDumych commented on @here/olp-sdk-fetch/README.md
> +The main goal of this module is to provide possibility to read files from the local folders with `fetch` API in the Node.js environment.
```suggestion
The main goal of this module is to provide the possibility to read files from the local folders with `fetch` API in the Node.js environment.
```

2024-05-09 11:20 UTC, HalynaDumych commented on CHANGELOG.md
> +- Remove node_fetch from the dependencies.
```suggestion
- Discontinued support of Node.js versions less than 18.x.
- Removed `node_fetch` from the dependencies.
```

2024-05-09 14:14 UTC, HalynaDumych submitted a review, later dismissed

2024-05-10 09:40 UTC, ystefinko approved these changes

2024-05-10 09:41 UTC, merged